#!/bin/bash

LOAD5=$(uptime | awk -F' *,? *' '{print $(NF-1)}')
LOAD=${LOAD5%%.*}
echo "로드율 $LOAD5   ${LOAD5%%.*}"
if [ $LOAD -ge 1 ]; then
echo "%CPU %MEM ARGS $(date)" >> ./ps.log
ps -e -o pcpu,pmem,args --sort=pcpu | cut -d" " -f1-5 | tail >> ./ps.log; sleep 5;
fi
